## PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.show-sql = true

# Creates tables if they don't exist but does not drop existing data
spring.jpa.hibernate.ddl-auto = update